import {
  Zap,
  Heart,
  Shield,
  Sword,
  Skull,
  Gift,
  Star,
  Crown,
  Flame,
  Sparkles,
  Wand2,
  Rocket,
  Bomb,
  Coins,
  Gem,
  Key,
  Lock,
  Unlock,
  Wrench,
  Hammer,
  Target,
  Radio,
  Megaphone,
  Flag,
  Map,
  Compass,
  Cloud,
  Sun,
  Moon,
  Package,
  Box,
  Axe,
  Bell,
  Bot,
  Cog,
  DollarSign,
  Droplets,
  Feather,
  Ghost,
  Globe2,
  Handshake,
  Plane,
  Rainbow,
  Snowflake,
  Timer,
  Trophy,
  UserCheck,
  UserX,
  Volume2,
  Wind,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  zap: Zap,
  heart: Heart,
  shield: Shield,
  sword: Sword,
  skull: Skull,
  gift: Gift,
  star: Star,
  crown: Crown,
  flame: Flame,
  sparkles: Sparkles,
  wand: Wand2,
  rocket: Rocket,
  bomb: Bomb,
  coins: Coins,
  gem: Gem,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  wrench: Wrench,
  hammer: Hammer,
  target: Target,
  radio: Radio,
  megaphone: Megaphone,
  flag: Flag,
  map: Map,
  compass: Compass,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
  package: Package,
  box: Box,
  axe: Axe,
  bell: Bell,
  bot: Bot,
  cog: Cog,
  dollar: DollarSign,
  droplets: Droplets,
  feather: Feather,
  ghost: Ghost,
  globe: Globe2,
  handshake: Handshake,
  plane: Plane,
  rainbow: Rainbow,
  snowflake: Snowflake,
  timer: Timer,
  trophy: Trophy,
  "user-check": UserCheck,
  "user-x": UserX,
  volume: Volume2,
  wind: Wind,
}

export const ICON_NAMES = Object.keys(ICON_MAP)

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Zap
}

// ============ COULEURS ============
// Palette limitee et coherente avec le design system du panel.

export const COLOR_MAP: Record<
  string,
  { text: string; bg: string; border: string; gradient: string; ring: string }
> = {
  primary: {
    text: "text-primary",
    bg: "from-primary/20 to-primary/5",
    border: "border-primary/25",
    gradient: "from-primary to-accent",
    ring: "ring-primary/30",
  },
  cyan: {
    text: "text-cyan-300",
    bg: "from-cyan-500/20 to-cyan-500/5",
    border: "border-cyan-500/25",
    gradient: "from-cyan-400 to-primary",
    ring: "ring-cyan-400/30",
  },
  green: {
    text: "text-green-400",
    bg: "from-green-500/20 to-green-500/5",
    border: "border-green-500/25",
    gradient: "from-green-400 to-emerald-500",
    ring: "ring-green-400/30",
  },
  yellow: {
    text: "text-yellow-400",
    bg: "from-yellow-500/20 to-yellow-500/5",
    border: "border-yellow-500/25",
    gradient: "from-yellow-400 to-orange-400",
    ring: "ring-yellow-400/30",
  },
  orange: {
    text: "text-orange-400",
    bg: "from-orange-500/20 to-orange-500/5",
    border: "border-orange-500/25",
    gradient: "from-orange-400 to-red-500",
    ring: "ring-orange-400/30",
  },
  red: {
    text: "text-red-400",
    bg: "from-red-500/20 to-red-500/5",
    border: "border-red-500/25",
    gradient: "from-red-500 to-orange-500",
    ring: "ring-red-400/30",
  },
  pink: {
    text: "text-pink-400",
    bg: "from-pink-500/20 to-pink-500/5",
    border: "border-pink-500/25",
    gradient: "from-pink-400 to-primary",
    ring: "ring-pink-400/30",
  },
  slate: {
    text: "text-slate-300",
    bg: "from-slate-500/20 to-slate-500/5",
    border: "border-slate-500/25",
    gradient: "from-slate-400 to-slate-500",
    ring: "ring-slate-400/30",
  },
}

export const COLOR_NAMES = Object.keys(COLOR_MAP)

export function getColor(name: string) {
  return COLOR_MAP[name] ?? COLOR_MAP.primary
}
